on:
  push:
    branches:
      - main
name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: readysteady

    #   - uses: actions/checkout@v2
    #     if: ${{ steps.release.outputs.release_created }}

    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version-file: '.node-version'
    #     if: ${{ steps.release.outputs.release_created }}

    #   - run: npm ci --ignore-scripts
    #     if: ${{ steps.release.outputs.release_created }}

    #   - run: npm run build
    #     if: ${{ steps.release.outputs.release_created }}

    #   - run: npm publish --production
    #     if: ${{ steps.release.outputs.release_created }}
