name: test

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
	  - run: node --version
	  - run: npm --version
	  - run: npm exec -- xo --version
      - run: npm test
        env:
          SMOKE_TEST_TOKEN: ${{ secrets.SMOKE_TESTS_ACCESS_TOKEN }}
