name: test

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

permissions:
  # downscope

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.SMOKE_TESTS_ACCESS_TOKEN }}
